# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml
# # import_playbook: ../static-assignments/common.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- hosts: all
- name: Include dynamic variables
  # tasks:
  # import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: db
- name: installing db
  import_playbook: ../static-assignments/db.yml

